apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: leaf-guard-app
spec:
  ingressClassName: nginx
  rules:
  - host: "a04a0053b787a46b3be2e68df6de08fb-dfc311b198885742.elb.ap-south-1.amazonaws.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ecsdemo-nodejs  # Replace with your service name
            port:
              number: 443  # Replace with your service port
