apiVersion: v1
kind: Service
metadata:
  name: ecsdemo-nodejs
spec:
  selector:
    app: ecsdemo-nodejs
  type: ClusterIP
  ports:
   -  port: 443
      protocol: TCP
      targetPort: 3000
      name: https
   -  port: 80
      protocol: TCP
      targetPort: 3000
      name: http

